# Generated by Django 4.2.1 on 2023-06-23 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='modelOrtu',
            fields=[
                ('id_ortu', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=250)),
                ('jenis_kelamin', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('nomor_telepon', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='modelPaket',
            fields=[
                ('id_paket', models.AutoField(primary_key=True, serialize=False)),
                ('nama_paket', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='modelPengajar',
            fields=[
                ('id_pengajar', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='modelSiswa',
            fields=[
                ('id_siswa', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('jenis_kelamin', models.CharField(max_length=50)),
                ('usia', models.IntegerField()),
                ('id_ortu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.modelortu')),
                ('id_paket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.modelpaket')),
            ],
        ),
        migrations.CreateModel(
            name='modelPendaftaran',
            fields=[
                ('no_pendaftaran', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal_pendaftaran', models.DateField(auto_now_add=True)),
                ('id_ortu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.modelortu')),
                ('id_siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.modelsiswa')),
            ],
        ),
        migrations.CreateModel(
            name='modelMapel',
            fields=[
                ('id_mapel', models.AutoField(primary_key=True, serialize=False)),
                ('nama_mapel', models.CharField(max_length=100)),
                ('id_paket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.modelpaket')),
                ('id_pengajar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.modelpengajar')),
            ],
        ),
    ]
