# Generated by Django 4.2.1 on 2023-05-13 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_model_nama_cabang'),
    ]

    operations = [
        migrations.CreateModel(
            name='modelMapel',
            fields=[
                ('id_mapel', models.AutoField(primary_key=True, serialize=False)),
                ('nama_mapel', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='modelOrtu',
            fields=[
                ('id_ortu', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('usia', models.IntegerField()),
                ('alamat', models.CharField(max_length=250)),
                ('jenis_kelamin', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('nomor_telepon', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='modelPaket',
            fields=[
                ('id_paket', models.AutoField(primary_key=True, serialize=False)),
                ('nama_paket', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='modelPendaftaran',
            fields=[
                ('no_pendaftaran', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal_pendaftaran', models.DateField(auto_now_add=True)),
                ('id_ortu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.modelortu')),
            ],
        ),
        migrations.CreateModel(
            name='modelPengajar',
            fields=[
                ('id_pengajar', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='modelSiswa',
            fields=[
                ('id_siswa', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('jenis_kelamin', models.CharField(max_length=50)),
                ('usia', models.IntegerField()),
                ('id_ortu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.modelortu')),
                ('id_paket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.modelpaket')),
            ],
        ),
        migrations.DeleteModel(
            name='Model',
        ),
        migrations.AddField(
            model_name='modelpendaftaran',
            name='id_siswa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.modelsiswa'),
        ),
        migrations.AddField(
            model_name='modelmapel',
            name='id_paket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.modelpaket'),
        ),
        migrations.AddField(
            model_name='modelmapel',
            name='id_pengajar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.modelpengajar'),
        ),
    ]
