# Generated by Django 4.2.1 on 2023-05-14 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_modelmapel_modelortu_modelpaket_modelpendaftaran_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelortu',
            name='usia',
        ),
    ]
