# Generated by Django 4.2.1 on 2023-05-14 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_modelortu_usia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelortu',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
